### ISSUE TITLE
Why do not the template use androidx viewmodel

### ISSUE THREAD

**Issue by oxyroid** [Kotlin/KMP-App-Template-Native#18]

**Comment by zsmb13** [comment]
It uses https://github.com/rickclephas/KMP-ObservableViewModel, which is the same as AndroidX ViewModel for the Android app, and provides a way for Swift code to observe changes in the shared ViewModel's state using `@StateViewModel`.

While there's a multiplatform version of the AndroidX ViewModel, it's primarily for use in shared UI apps where Compose runs on both platforms for now.
